import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-col items-center p-3 font-bold">
          <h2>useState, useRefの活用法について学べるサイトです。</h2>
          <h4>
            React Developer
            Toolsでレンダリングを可視化し、コンソールを開きながらボタンを押すとわかりやすいです!
          </h4>
        </div>
        {children}
      </body>
    </html>
  );
}
